[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.76"
wasm-bindgen = "0.2.99"
web-sys = { version = "0.3.76", features = ["Window", "Document", "HtmlCanvasElement", "CanvasRenderingContext2d"] }

[lib]
crate-type = ["cdylib"]
